variables:
  buildConfiguration: 'Release'

pool: HomePC

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Dev ops - Project Training '
    appType: 'webAppLinux'
    appName: 'training-cicd-webapp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'